"""Base indicator class that all indicators inherit from."""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Dict, Any, Optional
import pandas as pd
import numpy as np


@dataclass
class IndicatorSignal:
    """Signal generated by an indicator."""
    name: str
    timestamp: pd.Timestamp
    signal_type: str  # 'BUY', 'SELL', 'HOLD', 'OVERBOUGHT', 'OVERSOLD'
    value: float
    confidence: float  # 0.0 to 1.0
    metadata: Dict[str, Any] = field(default_factory=dict)


class BaseIndicator(ABC):
    """
    Base class for all technical indicators.
    
    All indicators must:
    1. Define their parameters with defaults
    2. Implement calculate() to compute values
    3. Implement get_signals() to generate trading signals
    4. Implement validate_inputs() to check data requirements
    """
    
    def __init__(self, name: str, params: Dict[str, Any]):
        """
        Initialize the indicator.
        
        Args:
            name: Display name of the indicator
            params: Dictionary of parameter values
        """
        self.name = name
        self.params = params
        self.values = None  # Will be a Series after calculate()
        self.validate_params()
    
    @abstractmethod
    def get_required_params(self) -> Dict[str, Any]:
        """
        Return the required parameters and their default values.
        
        Returns:
            Dict with parameter names as keys and default values
        """
        pass
    
    @abstractmethod
    def get_required_columns(self) -> list:
        """
        Return the list of DataFrame columns required for calculation.
        Usually: ['open', 'high', 'low', 'close', 'volume']
        """
        pass
    
    @abstractmethod
    def calculate(self, klines: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate the indicator values.
        
        Args:
            klines: DataFrame with OHLCV data
            
        Returns:
            DataFrame with indicator values added
        """
        pass
    
    @abstractmethod
    def get_signals(self, klines: pd.DataFrame) -> list:
        """
        Generate trading signals from the indicator.
        
        Args:
            klines: DataFrame with calculated indicator values
            
        Returns:
            List of IndicatorSignal objects
        """
        pass
    
    def validate_params(self):
        """Validate that all required parameters are provided."""
        required = self.get_required_params()
        for param_name, default_value in required.items():
            if param_name not in self.params:
                self.params[param_name] = default_value
    
    def validate_inputs(self, klines: pd.DataFrame) -> bool:
        """
        Validate that input DataFrame has required columns and data.
        
        Args:
            klines: DataFrame to validate
            
        Returns:
            True if valid, raises ValueError otherwise
        """
        required_cols = self.get_required_columns()
        
        # Check columns exist
        missing_cols = set(required_cols) - set(klines.columns)
        if missing_cols:
            raise ValueError(f"Missing columns for {self.name}: {missing_cols}")
        
        # Check minimum data length
        min_length = self._get_min_data_length()
        if len(klines) < min_length:
            raise ValueError(
                f"{self.name} requires at least {min_length} candles, "
                f"got {len(klines)}"
            )
        
        # Check for NaN values in required columns
        if klines[required_cols].isnull().any().any():
            raise ValueError(f"NaN values found in required columns for {self.name}")
        
        return True
    
    def _get_min_data_length(self) -> int:
        """
        Get the minimum number of candles required by this indicator.
        Override in subclasses if needed.
        """
        return 1
    
    def get_latest_signal(self, klines: pd.DataFrame) -> Optional[IndicatorSignal]:
        """
        Get the most recent signal from this indicator.
        
        Args:
            klines: DataFrame with calculated values
            
        Returns:
            Most recent IndicatorSignal or None
        """
        signals = self.get_signals(klines)
        return signals[-1] if signals else None
    
    def __repr__(self) -> str:
        return f"{self.name}({self.params})"
